title: Datayse
description: Datayse
author: Michael Ong
author_long: Michael Ong Ming Hao
github: https://github.com/Michaelomh
about: Michael's Journey with Data

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/michaelomh/"
    - icon: fa-github
      link: "https://github.com/Michaelomh"
    - icon: fa-behance-square
      link: "https://www.behance.net/MichaelOMH"
    - icon: fa-envelope
      link: "https://www.behance.net/MichaelOMH"

urls:
    - text: Search
      url: /search/
    - text: About
      url: /about/
    - text: Projects
      url: /projects/
    - text: Blog
      url: /blog/

url: "www.datayse.com"
baseurl: ""
paginate: 10
per_page: 10
paginate_path: "blog/page:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
