title: Michael's Personal Blog
description: Descriptions and Stuff
author: MICHAEL ONG
github: https://github.com/Michaelomh
about: About and Stuff

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/michaelomh/"
    - icon: fa-github
      link: "https://github.com/Michaelomh"
    - icon: fa-behance-square
      link: "https://www.behance.net/MichaelOMH"
    - icon: fa-email
      link: ""

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: Resume
      url: /resume/
    - text: Blog
      url: /blog/

url: "https://michaelomh.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
