title: Datayse
description: Datayse
author: Michael Ong
author_long: Michael Ong Ming Hao
github: https://github.com/Michaelomh
about: Michael's Adventures with Code

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/michaelomh/"
    - icon: fa-github
      link: "https://github.com/Michaelomh"
    - icon: fa-area-chart
      link: "https://public.tableau.com/profile/ong.ming.hao#!/"
#    - icon: fa-medium
#      link: "mailto:minghao.ong.2014@sis.smu.edu.sg?Subject=Hello"

urls:
    - text: About Me
      url: /about/
    - text: Portfolio
      url: /portfolio/
    - text: Timeline
      url: /timeline/
    - text: Search
      url: /search/

post_img_url: "http://www.datayse.com/static/img/_posts/"
url: "www.datayse.com"
baseurl: ""
paginate: 10
per_page: 10
paginate_path: "blog/page:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
