title: Datayse
description: Datayse
author: Michael Ong
author_long: Michael Ong Ming Hao
github: https://github.com/Michaelomh
about: Michael's Journey with Data

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin-square
      link: "https://www.linkedin.com/in/michaelomh/"
    - icon: fa-github-alt
      link: "https://github.com/Michaelomh"
    - icon: fa-bar-chart
      link: "https://public.tableau.com/profile/ong.ming.hao#!/"
    - icon: fa-envelope
      link: "mailto:minghao.ong.2014@sis.smu.edu.sg?Subject=Hello"

urls:
    - text: About
      url: /about/
    - text: Blog
      url: /blog/
    - text: Projects
      url: /projects/
    - text: Search
      url: /search/

post_img_url: "http://www.datayse.com/static/img/_posts/"
url: "www.datayse.com"
baseurl: ""
paginate: 10
per_page: 10
paginate_path: "blog/page:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
